First import tensorflow as tf as it is the widely used way. Now , tensorflow has its own datatypes for data analysis.
# Types of Datatype that Tensorflow offers are :
 1. int32
 2. int16
 3. float32
 4. string and many more... The complete list is here https://www.tensorflow.org/api_docs/python/tf/dtypes/DType
 
#### Tensors are multi-dimensional arrays with a uniform type (called a dtype). You can see all supported dtypes at tf.dtypes.DType. 
###### All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.


### Rank of tensors :

Def : "The rank of a tensor is analagous to representing a point in a dimension. For example representing a scalar on x-axis is a rank-0 tensor. Representing a vector on X,Y,Z space is a rank 1 tensor. A matrix is a rank-2 tensor." See more here https://mathworld.wolfram.com/TensorRank.html

Rank of a tensor can be found using `tf.rank(name of tensor)`

-------------------

### Shape of tensors
Def : "It is analogous to the order of a matrix i.e Rows x Columns. Since a tensor is an n-dimensional entity, it can have n-shapes. For example :"
The shape can be found using tensorname.shape

```
z = tf.constant(4) # z is a rank 0 tensor and its shape is null.
```
```
x = tf.Variable([2,4,5],tf.int32) # a is a rank 1 tensor (i.e a vector) and its shape is 3  
```

```
i = tf.Variable([[o,p],[q,r]] , tf.int16) # It has a rank of (2,2,5) .Note that this is a 3 dimensional matrix(i.e a tensor) 
```

In [23]:
import tensorflow as tf
import numpy as np

o = [1,2,3,5,6]
p = [4,5,6,89,9]
q = [5,6,7,89,6]
r = [34,6,6,43,3]
x = tf.Variable(o,tf.int32)
z = tf.constant(4)
i = tf.Variable([[o,p],[q,r]] , tf.int16)
print(z)
print(x)
print(i)
print()
print()
print(tf.rank(z))

tf.Tensor(4, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 5, 6], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2, 5) dtype=int32, numpy=
array([[[ 1,  2,  3,  5,  6],
        [ 4,  5,  6, 89,  9]],

       [[ 5,  6,  7, 89,  6],
        [34,  6,  6, 43,  3]]], dtype=int32)>


tf.Tensor(0, shape=(), dtype=int32)


# Reshaping tensors

In [40]:
m = [1,1,1,1,1]
p = [1,1,1,1,1]
e = [1,1,1,1,1]
o = [1,1,1,1,1]

_tensor = tf.Variable([[m,p],[e,o]] , tf.int16)
print(tf.rank(_tensor))
print(_tensor.shape)

print("\n\n\n")

#Make an unit tensor (analagous to unit matrix i.e matrix containing only 1)

unit_tensor = tf.ones([1,2,4]) #Mention the shape of the tensor as parameter in the form of a list
print(unit_tensor)

print("\n\n\n")

# lets reshape tensors now.

# syntax : tf.reshape( <tensorname> , <newshape>)

p = tf.reshape(unit_tensor , [4,1,2]) #Keep in mind that reshaping can only take place if the total number of elements remain the same in 
#both the original tensor and in the reshaped tensor. 
# Here , you cannot reshape the tensor into [4,5,6] because 4*5*6 will give 120 elements but our orginal [1,2,4] had only 1*2*4 = 8 elements.

print(p)

tf.Tensor(3, shape=(), dtype=int32)
(2, 2, 5)




tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(1, 2, 4), dtype=float32)




tf.Tensor(
[[[1. 1.]]

 [[1. 1.]]

 [[1. 1.]]

 [[1. 1.]]], shape=(4, 1, 2), dtype=float32)
